DELETE FROM folders WHERE standard_id = 6;
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (264, '一、加工贸易以及保税进出口业务', 6, 1, 2, 0, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (800, '1-进出口单证复核及保管制度', 6, 1, 2, 264, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (265, '二、卫生检疫业务', 6, 1, 2, 0, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (801, '2-特殊物品单证', 6, 1, 2, 265, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (802, '2023、I', 6, 1, 2, 801, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (803, '2023、II', 6, 1, 2, 801, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (804, '2024', 6, 1, 2, 801, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (805, '3-特殊物品安全管理制度', 6, 1, 2, 265, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (266, '三、动植物检疫业务', 6, 1, 2, 0, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (806, '4-商检制度与台账', 6, 1, 2, 266, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (807, '4-1-管理制度', 6, 1, 2, 806, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (808, '4-2-进境商检查验管理台账', 6, 1, 2, 806, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (809, '4-3-抽查单证', 6, 1, 2, 806, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (810, '4-4-熏蒸板记录', 6, 1, 2, 806, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (811, '三-4 商检制度', 6, 1, 2, 806, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (267, '五、进出口商品检验业务', 6, 1, 2, 0, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (812, '9-法检管理制度', 6, 1, 2, 267, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (300, '六、代理报关业务', 6, 1, 2, 0, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (813, '1-单证复核及系统逻辑检验', 6, 1, 2, 300, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (814, '1-1-进出口单证及复核制度文件', 6, 1, 2, 813, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (815, '1-2-系统复审界面截屏', 6, 1, 2, 813, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (816, '1-3-历年退改单率统计', 6, 1, 2, 813, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (817, '1-4-历年单一窗口数据取值截屏', 6, 1, 2, 813, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (818, '1-5-系统逻辑检验截屏', 6, 1, 2, 813, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (819, '1-6-历年单证抽取记录', 6, 1, 2, 813, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (820, '2-海关法律法规培训', 6, 1, 2, 300, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (821, '2-7-海关法律法规培训管理办法', 6, 1, 2, 820, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (822, '2-8-客户海关法律法规培训签到记录和培训课件', 6, 1, 2, 820, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (823, '3-延伸认证', 6, 1, 2, 300, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (824, '3-9-延伸认证情况说明文件', 6, 1, 2, 823, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (825, '六、1 单证复核及系统逻辑检验', 6, 1, 2, 300, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (826, '2.3 单证复核', 6, 1, 2, 825, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (827, '2.3、1 制度', 6, 1, 2, 826, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (828, '2.3、3 年度退改单率统计', 6, 1, 2, 826, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (829, '单一窗口数据取值截屏', 6, 1, 2, 828, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (830, '2.3、4 单证抽取2020~2024', 6, 1, 2, 826, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (831, '2020年度', 6, 1, 2, 830, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (832, '出口', 6, 1, 2, 831, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (833, '出境', 6, 1, 2, 831, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (834, '进口', 6, 1, 2, 831, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (835, '进境', 6, 1, 2, 831, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (836, '2021年度', 6, 1, 2, 830, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (837, '出口', 6, 1, 2, 836, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (838, '出境', 6, 1, 2, 836, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (839, '进口', 6, 1, 2, 836, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (840, '进境', 6, 1, 2, 836, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (841, '2022年度', 6, 1, 2, 830, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (842, '出口', 6, 1, 2, 841, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (843, '出境', 6, 1, 2, 841, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (844, '进口', 6, 1, 2, 841, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (845, '进境', 6, 1, 2, 841, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (846, '2023年度', 6, 1, 2, 830, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (847, '出口', 6, 1, 2, 846, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (848, '出境', 6, 1, 2, 846, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (849, '进口', 6, 1, 2, 846, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (850, '进境', 6, 1, 2, 846, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (851, '2024年度', 6, 1, 2, 830, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (852, '出口', 6, 1, 2, 851, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (853, '出境', 6, 1, 2, 851, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (854, '进口', 6, 1, 2, 851, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (855, '进境', 6, 1, 2, 851, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (856, '系统逻辑检验截屏', 6, 1, 2, 825, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (857, '六、2 海关法律法规培训', 6, 1, 2, 300, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (858, '客户培训记录', 6, 1, 2, 857, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (859, '2020年度', 6, 1, 2, 858, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (860, '培训课件', 6, 1, 2, 859, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (861, '2021年度', 6, 1, 2, 858, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (862, '培训课件', 6, 1, 2, 861, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (863, '2022年度', 6, 1, 2, 858, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (864, '培训课件', 6, 1, 2, 863, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (865, '2023年度', 6, 1, 2, 858, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (866, '课件', 6, 1, 2, 865, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (867, '2024年度', 6, 1, 2, 858, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (868, '课件', 6, 1, 2, 867, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (869, '240425保税区海关“智优营商 关助发展”惠企政策宣讲', 6, 1, 2, 868, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (870, '六、3 延伸认证', 6, 1, 2, 300, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (268, '八、物流运输业务', 6, 1, 2, 0, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (871, '20-运输工具管理制度', 6, 1, 2, 268, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (872, '21-运输工具行驶轨迹', 6, 1, 2, 268, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (873, '21-1-定位系统车载终端管理制度', 6, 1, 2, 872, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (874, '21-2-车辆行驶轨迹监控记录', 6, 1, 2, 872, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (875, '22-运输工具与驾驶人员匹配制度', 6, 1, 2, 268, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (876, '22-1-运输工具与驾驶人员匹配管理制度', 6, 1, 2, 875, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (877, '22-2-运输工具与驾驶人员匹配记录', 6, 1, 2, 875, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (878, '八、20 运输工具管理制度', 6, 1, 2, 268, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (879, '八、21 运输工具行驶轨迹', 6, 1, 2, 268, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (880, '八、21、1 制度', 6, 1, 2, 879, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (881, '八、21、2 轨迹记录', 6, 1, 2, 879, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (882, '八、22 运输工具与驾驶人员匹配制度', 6, 1, 2, 268, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (883, '八、22、1 制度', 6, 1, 2, 882, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (884, '八、22、2 记录', 6, 1, 2, 882, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (885, '八、22、2、1 车辆信息表', 6, 1, 2, 884, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (886, '八、22、2、2 提送货车辆登记表', 6, 1, 2, 884, NOW(), NOW(), '单项标准');