-- Standard 6 New Folder Structure
DELETE FROM `folders` WHERE `standard_id` = 6 AND `id` > 500;
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (700, '1-进出口单证复核及保管制度', 6, 1, 2, 264, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (701, '2-特殊物品单证', 6, 1, 2, 265, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (702, '2023、I', 6, 1, 2, 701, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (703, '2023、II', 6, 1, 2, 701, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (704, '2024', 6, 1, 2, 701, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (705, '3-特殊物品安全管理制度', 6, 1, 2, 265, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (706, '4-商检制度与台账', 6, 1, 2, 266, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (707, '4-1-进出境商检与进出口法检制度', 6, 1, 2, 706, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (708, '4-2-进境商检查验管理台账', 6, 1, 2, 706, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (709, '4-3-抽查单证', 6, 1, 2, 706, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (710, '4-4-熏蒸板记录', 6, 1, 2, 706, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (711, '9-进出境商检与进出口法检制度', 6, 1, 2, 267, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (712, '1-单证复核及系统逻辑检验', 6, 1, 2, 300, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (713, '1-1-进出口单证及复核制度文件', 6, 1, 2, 712, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (714, '1-2-系统复审界面截屏', 6, 1, 2, 712, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (715, '1-3-历年退改单率统计', 6, 1, 2, 712, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (716, '1-4-历年单一窗口数据取值截屏', 6, 1, 2, 712, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (717, '1-5-系统逻辑检验截屏', 6, 1, 2, 712, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (718, '1-6-历年单证抽取记录', 6, 1, 2, 712, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (719, '2.3 单证复核', 6, 1, 2, 712, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (720, '2.3、1 制度', 6, 1, 2, 719, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (721, '2.3、3 年度退改单率统计', 6, 1, 2, 719, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (722, '2.3、4 单证抽取2020~2024', 6, 1, 2, 719, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (723, '系统逻辑检验截屏', 6, 1, 2, 712, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (724, '2-海关法律法规培训', 6, 1, 2, 300, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (725, '2-7-海关法律法规培训管理办法', 6, 1, 2, 724, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (726, '2-8-客户海关法律法规培训签到记录和培训课件', 6, 1, 2, 724, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (727, '客户培训记录', 6, 1, 2, 724, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (728, '2020年度', 6, 1, 2, 727, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (729, '2021年度', 6, 1, 2, 727, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (730, '2022年度', 6, 1, 2, 727, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (731, '2023年度', 6, 1, 2, 727, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (732, '2024年度', 6, 1, 2, 727, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (733, '3-延伸认证', 6, 1, 2, 300, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (734, '3-9-延伸认证情况说明文件', 6, 1, 2, 733, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (735, '20-运输工具管理制度', 6, 1, 2, 268, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (736, '21-运输工具行驶轨迹', 6, 1, 2, 268, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (737, '21-1-定位系统车载终端管理制度', 6, 1, 2, 736, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (738, '21-2-车辆行驶轨迹监控记录', 6, 1, 2, 736, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (739, '八、21、1 制度', 6, 1, 2, 736, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (740, '八、21、2 轨迹记录', 6, 1, 2, 736, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (741, '22-运输工具与驾驶人员匹配制度', 6, 1, 2, 268, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (742, '22-1-运输工具与驾驶人员匹配管理制度', 6, 1, 2, 741, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (743, '22-2-运输工具与驾驶人员匹配记录', 6, 1, 2, 741, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (744, '八、22、1 制度', 6, 1, 2, 741, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (745, '八、22、2 记录', 6, 1, 2, 741, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (746, '八、22、2、1 车辆信息表', 6, 1, 2, 745, NOW(), NOW(), '单项标准');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (747, '八、22、2、2 提送货车辆登记表', 6, 1, 2, 745, NOW(), NOW(), '单项标准');
