INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (264, '一、加工贸易以及保税进出口业务', 6, 1, 2, 0, NOW(), NOW(), '关务');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (265, '二、卫生检疫业务', 6, 1, 2, 0, NOW(), NOW(), '关务');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (266, '三、动植物检疫业务', 6, 1, 2, 0, NOW(), NOW(), '关务');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (267, '五、进出口商品检验业务', 6, 1, 2, 0, NOW(), NOW(), '关务');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (268, '八、物流运输业务', 6, 1, 2, 0, NOW(), NOW(), '关务');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (300, '六、代理报关业务', 6, 1, 2, 0, NOW(), NOW(), '关务');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (269, '一、1 进出口单证复核&保管制度', 6, 1, 2, 264, NOW(), NOW(), '关务');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (372, '二、2 特殊物品单证', 6, 1, 2, 265, NOW(), NOW(), '关务');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (373, '二、3 特殊物品安全管理制度', 6, 1, 2, 265, NOW(), NOW(), '关务');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (377, '三、4 商检制度&台账', 6, 1, 2, 266, NOW(), NOW(), '关务');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (378, '五、9 法检制度', 6, 1, 2, 267, NOW(), NOW(), '关务');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (379, '八、20 运输工具管理制度', 6, 1, 2, 268, NOW(), NOW(), '关务');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (380, '八、21 运输工具行驶轨迹', 6, 1, 2, 268, NOW(), NOW(), '关务');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (383, '八、22 运输工具与驾驶人员匹配制度', 6, 1, 2, 268, NOW(), NOW(), '关务');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (381, '八、21、1 制度', 6, 1, 2, 380, NOW(), NOW(), '关务');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (382, '八、21、2 轨迹记录', 6, 1, 2, 380, NOW(), NOW(), '关务');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (384, '八、22、1 制度', 6, 1, 2, 383, NOW(), NOW(), '关务');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (385, '八、22、2 记录', 6, 1, 2, 383, NOW(), NOW(), '关务');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (311, '六、1 单证复核及系统逻辑检验', 6, 1, 2, 300, NOW(), NOW(), '关务');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (312, '六、2 海关法律法规培训', 6, 1, 2, 300, NOW(), NOW(), '关务');
INSERT INTO `folders` (`id`, `name`, `standard_id`, `user_id`, `master_id`, `parent_id`, `created_at`, `updated_at`, `department`) VALUES (313, '六、3 延伸认证', 6, 1, 2, 300, NOW(), NOW(), '关务');
